import type { Metadata } from "next";
import 'swiper/css';
import 'swiper/css/navigation';
import "./styles/globals.css";
import "./styles/custom.css";
import "./styles/rwd.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
