name: Deploy CasaQ Sites to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Infomaniak
    runs-on: ubuntu-latest

    steps:
      - name: Deploy through SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 57-111919.ssh.hosting-ik.com
          username: cBQSuYH4PSD_sitecasaq
          password: ${{ secrets.INFOMANIAK_SSH_PASSWORD }}
          script: |
            ~/deploy/deploy-sites-casaq.sh